import { FormEvent, ReactNode, useEffect, useRef, useState } from 'react';
import { Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { BadgeCheck, Camera, Gift, Home, LogOut, Menu, Mic, Music2, Shield, Swords, Upload, User, Video, X } from 'lucide-react';
import type { Session } from '@supabase/supabase-js';
import { configured, supabase } from './lib/supabase';
import type { LiveRoom, Profile, Role } from './types';

const EJAY_IMAGE='https://the-merge-music.lovable.app/__l5e/assets-v1/d466471d-69af-4352-b755-cf5f69b4dde3/ejay-papi-host.png';
const CATEGORIES=['artist','producer','dj','engineer','creator','fan'] as const;

function Auth({onReady}:{onReady:(s:Session)=>void}){
  const [mode,setMode]=useState<'login'|'signup'|'reset'>('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');
    if(!configured){setMsg('Backend setup required. Add Supabase environment variables.');setBusy(false);return;}
    if(mode==='reset'){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin});setMsg(error?.message||'Check your email for the reset link.');setBusy(false);return;}
    const result=mode==='signup'?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});
    if(result.error)setMsg(result.error.message); else if(result.data.session)onReady(result.data.session); else setMsg('Check your email to confirm your account.'); setBusy(false);
  }
  return <main className="auth"><section className="auth-card"><div className="brand"><Music2/> THE MERGE</div><p className="eyebrow">BY EJAY PAPI</p><h1>{mode==='signup'?'Create your profile':mode==='reset'?'Reset password':'Member login'}</h1><p className="muted">The community is available only to registered members.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label>{mode!=='reset'&&<label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required autoComplete={mode==='signup'?'new-password':'current-password'}/></label>}<button disabled={busy}>{busy?'Please wait…':mode==='signup'?'Create account':mode==='reset'?'Send reset link':'Log in'}</button></form>{msg&&<p className="notice">{msg}</p>}<div className="auth-links">{mode!=='login'&&<button onClick={()=>setMode('login')}>Log in</button>}{mode!=='signup'&&<button onClick={()=>setMode('signup')}>Create account</button>}{mode!=='reset'&&<button onClick={()=>setMode('reset')}>Forgot password?</button>}</div></section></main>
}

function Shell({session,role,children}:{session:Session;role:Role;children:ReactNode}){
 const [open,setOpen]=useState(false); const loc=useLocation(); useEffect(()=>setOpen(false),[loc.pathname]); useEffect(()=>{const fn=(e:KeyboardEvent)=>e.key==='Escape'&&setOpen(false);addEventListener('keydown',fn);return()=>removeEventListener('keydown',fn)},[]);
 const links=[['/','Home',Home],['/live','Live',Video],['/battle','Battles',Swords],['/upload','Upload / Submit',Upload],['/profile','My Profile',User],['/profiles/ejaypapi','EJAY PAPI',BadgeCheck]] as const;
 return <><header><button className="icon" aria-label="Open menu" onClick={()=>setOpen(true)}><Menu/></button><Link to="/" className="brand"><Music2/> THE MERGE</Link><span className="live-dot">LIVE</span></header>{open&&<div className="scrim" onMouseDown={()=>setOpen(false)}><aside onMouseDown={e=>e.stopPropagation()} aria-label="Main menu"><div className="drawer-head"><b>MENU</b><button className="icon" aria-label="Close menu" onClick={()=>setOpen(false)}><X/></button></div><nav>{links.map(([to,label,I])=><Link key={to} to={to}><I/>{label}</Link>)}{role!=='user'&&<Link to="/admin"><Shield/>Admin Dashboard</Link>}<button className="nav-logout" onClick={()=>supabase.auth.signOut()}><LogOut/>Log out</button></nav><small>{session.user.email}</small></aside></div>}<div className="page">{children}</div><footer>{links.slice(0,5).map(([to,label,I])=><Link aria-label={label} key={to} to={to} className={loc.pathname===to?'active':''}><I/><span>{label.split(' ')[0]}</span></Link>)}</footer></>
}

function HomePage(){return <><section className="hero"><p className="eyebrow">MUSIC • COMMUNITY • REAL CONNECTIONS</p><h1>Your sound belongs here.</h1><p>Join live rooms, build your profile, enter battles and connect with creators.</p><Link className="cta" to="/live">Go to Live</Link></section><section className="cards"><article><Mic/><h2>Live rooms</h2><p>Real room status and viewers—never fabricated.</p></article><article><Swords/><h2>Music battles</h2><p>Community competition and voting.</p></article><article><Gift/><h2>Gifting</h2><p>Unlocks after the secure coin and payment ledger is configured.</p></article></section></>}

function ProfilePage({session}:{session:Session}){const [p,setP]=useState<Partial<Profile>>({});const [msg,setMsg]=useState('');useEffect(()=>{supabase.from('profiles').select('*').eq('id',session.user.id).maybeSingle().then(({data})=>data&&setP(data))},[session.user.id]);async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.from('profiles').upsert({...p,id:session.user.id});setMsg(error?.message||'Profile saved.')}return <section><h1>My Profile</h1><form className="profile-form" onSubmit={save}><label>Display name<input required value={p.display_name||''} onChange={e=>setP({...p,display_name:e.target.value})}/></label><label>Username<input required value={p.username||''} onChange={e=>setP({...p,username:e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,'')})}/></label><label>Creator type<select value={p.creator_type||'fan'} onChange={e=>setP({...p,creator_type:e.target.value})}><option>fan</option><option>artist</option><option>producer</option><option>DJ</option><option>engineer</option><option>creator</option></select></label><div className="two"><label>City<input value={p.city||''} onChange={e=>setP({...p,city:e.target.value})}/></label><label>State<input maxLength={2} value={p.state||''} onChange={e=>setP({...p,state:e.target.value.toUpperCase()})}/></label></div><label>Photo URL<input value={p.avatar_url||''} onChange={e=>setP({...p,avatar_url:e.target.value})}/></label><label>Bio<textarea value={p.bio||''} onChange={e=>setP({...p,bio:e.target.value})}/></label><button>Save profile</button>{msg&&<p className="notice">{msg}</p>}</form></section>}

function Ejay(){return <section className="official"><img src={EJAY_IMAGE} alt="EJAY PAPI wearing headphones"/><h1>EJAY PAPI <BadgeCheck/></h1><p>@ejaypapi • Host • Orlando, FL</p><p>Official host of The Merge—real conversations, music and community connections.</p><div className="empty-stat">Followers: 0&nbsp;&nbsp; Following: 0&nbsp;&nbsp; Plays: 0</div></section>}

function CameraTest(){const video=useRef<HTMLVideoElement>(null);const [stream,setStream]=useState<MediaStream|null>(null);const [error,setError]=useState('');async function enable(){try{const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});setStream(s);if(video.current)video.current.srcObject=s}catch(e){setError(e instanceof Error?e.message:'Camera or microphone permission denied.')}}function stop(){stream?.getTracks().forEach(t=>t.stop());setStream(null);if(video.current)video.current.srcObject=null}useEffect(()=>()=>stream?.getTracks().forEach(t=>t.stop()),[stream]);return <div className="camera"><video ref={video} autoPlay playsInline muted/><div className="camera-actions">{!stream?<button onClick={enable}><Camera/>Enable camera & microphone</button>:<button onClick={stop}><X/>Stop test</button>}</div>{error&&<p className="notice">Allow camera and microphone in your browser settings, then try again. {error}</p>}</div>}

function LivePage({session}:{session:Session}){const [rooms,setRooms]=useState<LiveRoom[]>([]);const [viewers,setViewers]=useState(0);useEffect(()=>{const load=()=>supabase.from('live_rooms').select('*').eq('status','live').then(({data})=>setRooms(data||[]));load();const changes=supabase.channel('live-room-changes').on('postgres_changes',{event:'*',schema:'public',table:'live_rooms'},load).subscribe();const presence=supabase.channel('global-live-presence',{config:{presence:{key:session.user.id}}});presence.on('presence',{event:'sync'},()=>setViewers(Object.keys(presence.presenceState()).length)).subscribe(async s=>{if(s==='SUBSCRIBED')await presence.track({online_at:new Date().toISOString()})});return()=>{supabase.removeChannel(changes);supabase.removeChannel(presence)}},[session.user.id]);return <section><h1>Live</h1><div className="category-grid">{CATEGORIES.map(c=><Link to={`/directory/${c}`} key={c}>{c==='dj'?'DJs':`${c[0].toUpperCase()}${c.slice(1)}s`}</Link>)}</div><div className="status"><span className={rooms.length?'on':'off'}/><b>{rooms.length?`${rooms.length} live room${rooms.length>1?'s':''}`:'No one is live right now'}</b><small>{viewers} authenticated viewer{viewers===1?'':'s'} online</small></div><CameraTest/><p className="muted">This device test uses your real camera and microphone. Large-audience broadcasting stays disabled until LiveKit is connected; the app will not pretend a local preview is a public stream.</p></section>}

function Directory(){const category=useLocation().pathname.split('/').pop()||'artist';const [people,setPeople]=useState<Profile[]>([]);useEffect(()=>{supabase.from('profiles').select('*').ilike('creator_type',category).eq('is_suspended',false).order('display_name').then(({data})=>setPeople(data||[]))},[category]);return <section><h1>{category==='dj'?'DJs':`${category}s`}</h1><div className="directory">{people.length?people.map(p=><article key={p.id}>{p.avatar_url?<img src={p.avatar_url} alt=""/>:<User/>}<div><b>{p.display_name}</b><small>@{p.username}{p.city?` • ${p.city}${p.state?', '+p.state:''}`:''}</small></div></article>):<p className="muted">No registered {category}s yet. New profiles will appear here automatically.</p>}</div></section>}

function Admin({role}:{role:Role}){const [profiles,setProfiles]=useState<Profile[]>([]);const [rooms,setRooms]=useState<LiveRoom[]>([]);useEffect(()=>{if(role!=='user'){supabase.from('profiles').select('*').order('created_at',{ascending:false}).then(({data})=>setProfiles(data||[]));supabase.from('live_rooms').select('*').order('created_at',{ascending:false}).then(({data})=>setRooms(data||[]))}},[role]);if(role==='user')return <Navigate to="/"/>;return <section><h1>Admin Dashboard</h1><div className="metrics"><article><b>{profiles.length}</b><span>Users</span></article><article><b>{rooms.filter(r=>r.status==='live').length}</b><span>Live now</span></article></div><h2>Users</h2><div className="table">{profiles.length?profiles.map(p=><div key={p.id}><span>{p.display_name||p.username}</span><small>@{p.username} • {p.is_suspended?'Suspended':'Active'}</small></div>):<p>No registered users found.</p>}</div></section>}

function Placeholder({title}:{title:string}){return <section><h1>{title}</h1><p className="muted">This section is connected to authenticated navigation. Database workflows are being activated without demo records.</p></section>}

export function App(){const [session,setSession]=useState<Session|null|undefined>(undefined);const [role,setRole]=useState<Role>('user');useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);useEffect(()=>{if(session)supabase.rpc('current_user_role').then(({data})=>setRole((data as Role)||'user'));else setRole('user')},[session]);if(session===undefined)return <div className="splash">Loading The Merge…</div>;if(!session)return <Auth onReady={setSession}/>;return <Shell session={session} role={role}><Routes><Route path="/" element={<HomePage/>}/><Route path="/live" element={<LivePage session={session}/>}/><Route path="/battle" element={<Placeholder title="Music Battles"/>}/><Route path="/upload" element={<Placeholder title="Upload / Submit"/>}/><Route path="/profile" element={<ProfilePage session={session}/>}/><Route path="/profiles/ejaypapi" element={<Ejay/>}/><Route path="/directory/:category" element={<Directory/>}/><Route path="/admin" element={<Admin role={role}/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></Shell>}
